image: python:3.9-slim

variables:
  AWS_EC2_HOST: $AWS_EC2_HOST
  EC2_IP: $EC2_IP
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
  IMAGE_TAG: $CI_COMMIT_REF_SLUG
  IMAGE_NAME: $CI_REGISTRY_IMAGE

stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

  script:
    - docker build -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - prod

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/test.pem
    - chmod 600 ~/.ssh/test.pem
    - head -n 1 ~/.ssh/test.pem
    - ls -la ~/.ssh/test.pem
    - ssh -v -T -o StrictHostKeyChecking=no -i ~/.ssh/test.pem ubuntu@${EC2_IP} 'exit'
  script:
    - |
      ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/test.pem ubuntu@${EC2_IP} << 'EOF'
        # Login to Docker registry
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

        docker pull $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

        # Stop/remove old container
        docker stop fastapi-app || true
        docker rm -f fastapi-app || true

        # Run new container with environment variables, restart policy, and health checks
        docker run -d \
          --name fastapi-app \
          -p 8090:8090 \
          --restart unless-stopped \
          $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

        # Clean up unused images (avoid pruning everything!)
        docker image prune -af --filter "until=24h"
      EOF
  only:
    - prod
